name: "Upstream release"
description: "Perform an upstream GitHub release"

inputs:
  token:
    description: "A GitHub token for creating a release"
    required: true
  slack_webhook_url:
    description: "A Slack incoming Webhook URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
          token: "${{ inputs.TOKEN }}"
          fetch-depth: 0

    - name: Fetch all tags
      # GitHub's checkout action doesn't properly fetch the current tag
      run: git fetch --tags --prune --force
      shell: bash

    - name: Generate release information
      run: ${{ github.action_path }}/release-info.sh
      shell: bash

    - name: Create GitHub release
      # https://github.com/marketplace/actions/create-release
      uses: ncipollo/release-action@v1.8.10
      with:
        name: "${{  env.release_version }}"
        token: "${{ inputs.TOKEN }}"
        bodyFile: "release.md"

    - name: Bump version
      run: ${{ github.action_path }}/bump-version.sh "${{  env.release_version }}"
      shell: bash

    - name: Commit new version
      # https://github.com/marketplace/actions/add-commit
      uses: EndBug/add-and-commit@v7
      if: github.ref == 'refs/heads/main'
      with:
        branch: main
        message: "Post release version bump\n\n[skip ci]"
        add: "-u *"

    - name: Send release announcement to osbuild Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: "{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"🚀 *<https://github.com/osbuild/${{  env.component }}/releases/tag/v${{  env.release_version }}|${{  env.component }} ${{  env.release_version }}>* just got released upstream! 🚀\"}}]}"
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK