name: "Upstream release"
description: "Perform an upstream GitHub release"

inputs:
  token:
    description: "A GitHub token for creating a release"
    required: true
  slack_bot_token:
    description: "A Slack bot OAuth token"
    required: true
  build_release_artifacts:
    description: "Run `make release_artifacts` and expect results in `release_artifacts/`"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
          token: "${{ inputs.TOKEN }}"
          fetch-depth: 0

    - name: Fetch all tags
      # GitHub's checkout action doesn't properly fetch the current tag
      run: git fetch --tags --prune --force
      shell: bash

    - name: Generate release information
      run: ${{ github.action_path }}/release-info.sh
      shell: bash

    - name: Build additional release artifacts (optionally)
      run: make release_artifacts
      shell: bash
      if: ${{ inputs.build_release_artifacts == 'true' }}

    - name: Create GitHub release
      # https://github.com/marketplace/actions/create-release
      uses: ncipollo/release-action@v1.14.0
      with:
        name: "${{  env.release_version }}"
        token: "${{ inputs.TOKEN }}"
        bodyFile: "release.md"
        artifacts: "release_artifacts/*"

    - name: Bump version
      run: ${{ github.action_path }}/bump-version.sh "${{  env.release_version }}"
      shell: bash

    - name: Commit new version
      # https://github.com/marketplace/actions/add-commit
      uses: EndBug/add-and-commit@v7
      with:
        branch: main
        message: "Post release version bump\n\n[skip ci]"
        add: "-u *"

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Send release announcement to osbuild Slack channel
      run: |
        python3 ${{ github.action_path }}/slack_notify_release.py \
          --component "${{ env.component }}" \
          --version "${{ env.release_version }}" \
          --release-notes-file "release.md" \
          --slack-bot-token "${{ inputs.slack_bot_token }}" \
          --slack-channel-id "${{ vars.SLACK_CHANNEL_ID }}"
      shell: bash
