name: "Release bot"
description: "Create a tag and push it"

inputs:
  token:
    description: "A GitHub token for creating a tag"
    required: true
  username:
    description: "A GitHub user name"
    required: true
  email:
    description: "The GitHub user's email address"
    required: true
  semver:
    description: "Use semantic versioning instead of a single number"
    required: false
    default: "false"
  semver_bump_type:
    description: "The type of semantic versioning bump to perform. Can be 'major', 'minor', or 'patch'."
    required: false
    default: "major"

runs:
  using: "composite"
  steps:
    - name: Checkout current repo
      uses: actions/checkout@v3
      with:
          token: "${{ inputs.TOKEN }}"
          fetch-depth: 0

    - name: Install Python and depends
      run: |
        sudo apt install python3
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Get component name
      run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      shell: bash

    - name: Set up git
      run:  |
        git clone https://"${{ inputs.TOKEN }}"@github.com/"${{ github.repository }}".git ${{ github.action_path }}/${{ env.REPOSITORY_NAME }}
        git config --global user.email "${{ inputs.EMAIL }}"
        git config --global user.name "${{ inputs.USERNAME }}"
      shell: bash

    - name: Create and push tag
      env:
        BASE_BRANCH: ${{ env.GITHUB_REF_NAME }}
      run: |
        cd ${{ github.action_path }}/${{ env.REPOSITORY_NAME }}/
        if [[ "${{ inputs.SEMVER }}" == "true" ]]; then
          VERSION_TYPE_OPTION="--semver"
        else
          VERSION_TYPE_OPTION=""
        fi
        if [[ "${{ inputs.SEMVER_BUMP_TYPE }}" != "" ]]; then
          VERSION_TYPE_OPTION="$VERSION_TYPE_OPTION --semver-bump-type ${{ inputs.SEMVER_BUMP_TYPE }}"
        fi
        if [[ -n ${{ env.BASE_BRANCH }} ]]; then
          BASE_BRANCH_OPTION="--base ${{ env.BASE_BRANCH }}"
        fi
        ${{ github.action_path }}/create_tag.py --token "${{ inputs.TOKEN }}" $VERSION_TYPE_OPTION $BASE_BRANCH_OPTION
      shell: bash
